### ISSUE TITLE
bug lors de l'import d'un fichier CSV

### ISSUE THREAD

**Issue by simonLouvet** [assemblee-virtuelle/Semantic-Bus#4]
Error
    at readStream (/home/busdev/GIT/Semantic-Bus/node_modules/raw-body/index.js:196:17)
    at getRawBody (/home/busdev/GIT/Semantic-Bus/node_modules/raw-body/index.js:106:12)
    at read (/home/busdev/GIT/Semantic-Bus/node_modules/body-parser/lib/read.js:76:3)
    at jsonParser (/home/busdev/GIT/Semantic-Bus/node_modules/body-parser/lib/types/json.js:121:5)
    at Layer.handle [as handle_request] (/home/busdev/GIT/Semantic-Bus/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/busdev/GIT/Semantic-Bus/node_modules/express/lib/router/index.js:312:13)
    at /home/busdev/GIT/Semantic-Bus/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/busdev/GIT/Semantic-Bus/node_modules/express/lib/router/index.js:330:12)
    at next (/home/busdev/GIT/Semantic-Bus/node_modules/express/lib/router/index.js:271:10)
    at initialize (/home/busdev/GIT/Semantic-Bus/node_modules/passport/lib/middleware/initialize.js:53:5)
    at Layer.handle [as handle_request] (/home/busdev/GIT/Semantic-Bus/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/busdev/GIT/Semantic-Bus/node_modules/express/lib/router/index.js:312:13)
    at /home/busdev/GIT/Semantic-Bus/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/busdev/GIT/Semantic-Bus/node_modules/express/lib/router/index.js:330:12)
    at next (/home/busdev/GIT/Semantic-Bus/node_modules/express/lib/router/index.js:271:10)
    at cors (/home/busdev/GIT/Semantic-Bus/node_modules/cors/lib/index.js:179:7)
    at /home/busdev/GIT/Semantic-Bus/node_modules/cors/lib/index.js:229:17
    at originCallback (/home/busdev/GIT/Semantic-Bus/node_modules/cors/lib/index.js:218:15)
    at /home/busdev/GIT/Semantic-Bus/node_modules/cors/lib/index.js:223:13
    at optionsCallback (/home/busdev/GIT/Semantic-Bus/node_modules/cors/lib/index.js:204:9)
    at corsMiddleware (/home/busdev/GIT/Semantic-Bus/node_modules/cors/lib/index.js:209:7)
    at Layer.handle [as handle_request] (/home/busdev/GIT/Semantic-Bus/node_modules/express/lib/router/layer.js:95:5)

**Comment by simonLouvet** [comment]
https://support.spatialkey.com/spatialkey-sample-csv-data/

**Comment by alex3144** [comment]
Taille du fichier je pense

Envoyé de mon iPhone

Le 3 juil. 2017 à 20:59, simonLouvet <notifications@github.com<mailto:notifications@github.com>> a écrit :


Closed #4<https://github.com/assemblee-virtuelle/Semantic-Bus/issues/4>.
